config/routes.rb
Rails.application.routes.draw do

  root 'landings#index'

  resources :landings, only: [:index]
  resources :dashboards, only: [:index]

  resources :boards do
    resources :tasks
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @tasks = @board.tasks
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to @board, notice: 'Board was succesfully creates.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to @board, notice: 'Board was succesfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, notice: 'Board was succesfully destroyed.'
  end


  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
  end
  
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController

  def index
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :set_board, only: [:new, :create, :edit, :update, :destroy]
  before_filter :set_task, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @task = @board.tasks.new
  end

  def create
    @task = @board.tasks.new(task_params)
    if @task.save
      redirect_to @board, notice: 'Task was succesfully creates.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @board, notice: 'Task was succesfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to @board, notice: 'Board was succesfully destroyed.'
  end

  private

  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_task
    @task = Board.find(params[:board_id]).tasks.find(params[:id])
  end


  def task_params
    params.require(:task).permit(:title, :task_start, :task_finish)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_for @board do |f| %>

  <% if @board.errors.any? %>
    <div>
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.submit %>
  </div>



<% end %>

app/views/boards/edit.html.erb
<h1>Edit board title</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-lg-12'>
      <h1 class='page-header'>Boards</h1>
    </div>
  </div>

  <div class='container-fluid'>
    <div class='row'>
      <div class='col-ld-12'>
        <%= link_to 'New board', new_board_path, class: 'btn btn-outline btn-primary btn-lg btn-block' %>
      </div>
    </div>
  </div>

</br>


  <div class='row'>

    <% @boards.each do |board| %>
        <div class='col-lg-3 col-md-6'>
          <div class='panel panel-primary'>
            <div class='panel-heading'>
      <%= link_to board, class: 'board' do %>
              <div class='row'>
                <div class='col-xs-3'>
                  <i class="fa fa-tasks fa-5x"></i>
                </div>
                <div class='col-xs-9 text-right'>
                  <div><%= board.title %></div>
                  <div>Tasks to do: <%= board.tasks.count %></div>
                </div>
              </div>
      <% end %>
            </div>
            <div class='panel-footer'>
              <%= link_to 'Show', board, class: 'pull-left' %>
              <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
              <div class='clearfix'></div>
            </div>

            <div class='panel-footer'>
              <%= link_to 'Destroy board', board, method: :delete, data: { confirm: 'Are you sure?'} %>
            </div>
          </div>
        </div>
    <% end %>

  </div>

</div>

app/views/boards/new.html.erb
<h1>Add new board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<h1><%= @board.title %> </h1>

<%= link_to 'New task', new_board_task_path(@board) %>

<% @tasks.each do |task| %>
  <div>
    <%= task.title %>
    <%= link_to 'Show', board_task_path(task.board, task) %>
    <%= link_to 'Edit', edit_board_task_path(task.board, task) %>
    <%= link_to 'Delete task', board_task_path(task.board, task), method: :delete,
                                          data: { confirm: 'Are you sure?'} %>
  </div>  

<% end %>

<%= link_to 'Back', boards_path %>

app/views/dashboards/index.html.erb
<div class='container-fluid'>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Dashboard</h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->

  <div class="row">
    <div class="col-lg-3 col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">
                    <i class="fa fa-comments fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                    <div class="huge">26</div>
                    <div>New Comments!</div>
                </div>
            </div>
        </div>
        <a href="#">
            <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
            </div>
        </a>
    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">12</div>
                                    <div>New Tasks!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">124</div>
                                    <div>New Orders!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">13</div>
                                    <div>Support Tickets!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>

</div>

app/views/landings/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Please Sign In</h3>
        </div>
        <div class="panel-body">
          <form role="form">
            <fieldset>
              <div class="form-group">
                <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>
              </div>
              <div class="form-group">
                <input class="form-control" placeholder="Password" name="password" type="password" value="">
              </div>
              <div class="checkbox">
                <label>
                  <input name="remember" type="checkbox" value="Remember Me">Remember Me
                </label>
              </div>
              <!-- Change this to a button or input when using this as a form -->
              <a href="index.html" class="btn btn-lg btn-success btn-block">Login</a>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Organizer dashboard', boards_path, class: 'navbar-brand' %>
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right">

    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a></li>
        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a></li>
        <li class="divider"></li>
        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
      </ul>
          <!-- /.dropdown-user -->
    </li>
        <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <%= render 'layouts/navigation_sidebar' %>  
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>

app/views/layouts/_navigation_sidebar.html.erb
<ul class="nav" id="side-menu">
  <li>
    <%= link_to '<i class="fa fa-dashboard fa-fw"></i> Dashboard'.html_safe, dashboards_path %>
  </li>
  <li>
    <%= link_to '<i class="fa fa-table fa-fw"></i> Boards'.html_safe, boards_path %>
  </li>
  <li>
    <%= link_to '<i class="fa fa-edit fa-fw"></i> Addresses'.html_safe, boards_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Organizer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">
    
    <%= render 'layouts/navigation' %>

    <div id="page-wrapper">

    <%= yield %>

    </div>
    <!-- /#page-wrapper -->
  
  </div>
  <!-- /#wrapper --> 



</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for([@board, @task]) do |f| %>
    
  <% if @task.errors.any? %>
    <div>
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :task_start %>
    <%= f.date_field :task_start %>
  </div>

  <div>
    <%= f.label :task_finish %>
    <%= f.date_field :task_finish %>
  </div>

  <div>
    <%= f.submit %>
  </div>


<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task title</h1>

<%= render 'form' %>

<%= link_to 'Back', board_path(params[:board_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', board_path(params[:board_id]) %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<%= link_to 'Back', board_path(@task.board) %>